server:
  port: 8000

mybatis-plus:
  mapper-locations: classpath:com/atguigu/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: shop-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.208:8848
  rabbitmq:
    host: 192.168.18.208
    port: 5672
    username: admin
    password: 123
  redis:
    host: 192.168.18.208
    port: 6389
    database: 0
    timeout: 1800000
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.18.208:3306/shop_product?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  shardingsphere:
    datasource:
      #真实物理数据库名称
      names: write-node1,read-node1,read-node2
      write-node1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.18.208:3306/shop_product_01?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
      read-node1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.18.208:3306/shop_product_02?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
      read-node2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.18.208:3306/shop_product_03?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
    #读写分类策略
    rules:
      readwrite-splitting:
        data-sources:
          master-node:
            type: Static
            props:
              #自动发现数据源是哪个
              auto-aware-data-source-name: master-node
              #写数据源是写哪个
              write-data-source-name: write-node1
              #读数据从哪个读 多个数据源用逗号
              read-data-source-names: read-node1,read-node2
            #负载均衡算法名称
            loadBalancerName: read-lb
          loadBalancers:
            read-lb:
              type: ROUND_ROBIN

















minio:
  endpoint: http://47.106.67.192:9000
  access-key: enjoy6288
  secret-key: enjoy6288
  bucket-name: java0212



